---
# General Site Settings
title: Tsunderick
# You can add own logo for the navbar. For example '/images/logo.png'.
# logo:
description: Welcome to my realm mortals!
# The subpath of your site, e.g. /blog
# baseurl: "/new-blog-test"
baseurl: ""
url: "https://erick-garcia.com"

# Author Settings
author:
  name: Tsunderick
  avatar: "/images/senjougahara.jpg"

# Hero Settings
hero:
  title: Erick Garcia
  description: Keep it simple
  image: "/images/Ilya_Kuvshinov-nature.jpg"

# Contact Settings
contact:
  email: contact@erick-garcia.com
  description: Send me an email through this form to contact@erick-garcia.com

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

# Footer section
# Other icons can be found at https://ionicons.com
social:
  - { icon: "ion-logo-twitter", link: "https://twitter.com/tsunderick" }
  - { icon: "ion-logo-instagram", link: "https://www.instagram.com/tsunderick" }
  - { icon: "ion ion-logo-github", link: "https://github.com/garciaErick" }
  - {
      icon: "ion ion-logo-linkedin",
      link: "https://linkedin.com/in/garciaErickCs",
    }
  - {
      icon: "ion ion-logo-steam",
      link: "https://steamcommunity.com/id/tsunderick",
    }
  - {
      icon: "ion ion-logo-youtube",
      link: "https://www.youtube.com/blaksephirot",
    }

# Comment Section (Disqus)
# Add your shortname for Disqus Comment. For example mr-brown
disqus-identifier: tsunderick

# Google Analytics
google-analytics: UA-114039103-1 

#-------------------------------
# Newsletter
# To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp: true
mailchimp-identifier: erick-garcia.us17.list-manage.com/subscribe?u=898ccc96d660b961b95cfd82c&id=fb57b2e849

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed
  - jekyll-seo-tag

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed

# Jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 9
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
